/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yWCFB0y9jI0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"

export function taskcard() {
  return (
    <div className="container mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="flex justify-center mb-8">
        <div className="w-full max-w-md">
          <div className="flex items-center space-x-4">
            <Input
              className="flex-1 rounded-md border-gray-300 shadow-sm focus:border-primary focus:ring-primary"
              placeholder="Enter a task"
              type="text"
            />
            <Button className="rounded-md bg-primary px-4 py-2 text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2">
              Generate
            </Button>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-medium">Clean the kitchen</h3>
            <Checkbox id="task-1" />
          </div>
          <p className="text-gray-500 mb-4">Wipe down counters, sweep and mop the floor, and load the dishwasher.</p>
        </div>
        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-medium">Grocery shopping</h3>
            <Checkbox id="task-2" />
          </div>
          <p className="text-gray-500 mb-4">Pick up milk, eggs, bread, and other essentials from the store.</p>
        </div>
        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-medium">Laundry</h3>
            <Checkbox id="task-3" />
          </div>
          <p className="text-gray-500 mb-4">Wash, dry, and fold all the clothes in the hamper.</p>
        </div>
        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-medium">Take out the trash</h3>
            <Checkbox id="task-4" />
          </div>
          <p className="text-gray-500 mb-4">Gather all the trash from around the house and take it to the curb.</p>
        </div>
      </div>
    </div>
  )
}
